In [2]:
1+1

2

In [3]:
1+1 #덧셈

2

In [6]:
for i in range(3):
    print(i)

0
1
2


In [7]:
'ㅇㄹㄴㄹㅇ'

'ㅇㄹㄴㄹㅇ'

In [8]:
"ㅇㅇㄴㄹㄴ"

'ㅇㅇㄴㄹㄴ'

In [9]:
def udf_01(x):
    print(x)

In [11]:
import numpy as np

np.array([1,2,3])
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [12]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
array = np.array([[1,2,3], [4,5,6]])

In [15]:
array[0]

array([1, 2, 3])

In [16]:
array[1]

array([4, 5, 6])

In [17]:
array[0, :2]

array([1, 2])

In [18]:
array[0, 2]

3

In [19]:
nums = np.array([1,2,2,3])

In [23]:
set(nums)

{1, 2, 3}

In [22]:
np.unique(nums)

array([1, 2, 3])

In [24]:
len(nums)

4

In [25]:
np.arange(3,8,2)

array([3, 5, 7])

In [26]:
np.where(nums == 2,1,0)

array([0, 1, 1, 0])

In [27]:
import pandas as pd

ser = pd.Series([1,2,3])
ser

0    1
1    2
2    3
dtype: int64

In [30]:
import pandas as pd
import numpy as np



In [32]:
df = pd.read_csv("iris.csv")
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
df["is_setosa"] = np.where(df["Species"] == "setosa", 1,0)
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  is_setosa
0           5.1          3.5           1.4          0.2  setosa          1
1           4.9          3.0           1.4          0.2  setosa          1
2           4.7          3.2           1.3          0.2  setosa          1
3           4.6          3.1           1.5          0.2  setosa          1
4           5.0          3.6           1.4          0.2  setosa          1

In [35]:
pd.crosstab(df["Species"], df["is_setosa"])

is_setosa    0   1
Species           
setosa       0  50
versicolor  50   0
virginica   50   0